"""Initial db.

Revision ID: 6c8454431644
Revises: 
Create Date: 2020-07-20 11:23:34.644592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8454431644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('schema', sa.String(length=64), nullable=False),
    sa.Column('table', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Seeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('digest', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('Jobs',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=32), nullable=False),
    sa.Column('submit_type', sa.Enum('hddsn', 'hddtrial', 'csv', name='submittype'), nullable=True),
    sa.Column('treatment_name', sa.String(length=32), nullable=False),
    sa.Column('control_name', sa.String(length=32), nullable=False),
    sa.Column('use_control_list', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('analytics_level', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('target_data', sa.String(length=32), nullable=False),
    sa.Column('match_key_p_mode', sa.Enum('Auto', 'Custom', name='matchkeypmode'), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=128), nullable=True),
    sa.Column('user_email', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Jobs')
    op.drop_table('Users')
    op.drop_table('Seeds')
    op.drop_table('Products')
    # ### end Alembic commands ###
